/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-02-25

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32f10x.h"
GPIO_InitTypeDef Gpio_InitStruct;
EXTI_InitTypeDef Exti_InitStruct;
NVIC_InitTypeDef NVIC_InitStruct;
void Gpio_Config(){

	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA,ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOB,ENABLE);
	Gpio_InitStruct.GPIO_Mode=GPIO_Mode_Out_PP;
	Gpio_InitStruct.GPIO_Speed=GPIO_Speed_50MHz;
	Gpio_InitStruct.GPIO_Pin=GPIO_Pin_2|GPIO_Pin_3|GPIO_Pin_4|GPIO_Pin_5;
	GPIO_Init(GPIOB,&Gpio_InitStruct);
	Gpio_InitStruct.GPIO_Mode=GPIO_Mode_IPD;
	Gpio_InitStruct.GPIO_Speed=GPIO_Speed_50MHz;
	Gpio_InitStruct.GPIO_Pin=GPIO_Pin_2|GPIO_Pin_3;
	GPIO_Init(GPIOA,&Gpio_InitStruct);



}
void Exti_Config(){
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO,ENABLE);
	Exti_InitStruct.EXTI_Line=EXTI_Line2|EXTI_Line3;
	Exti_InitStruct.EXTI_Mode=EXTI_Mode_Interrupt;
	Exti_InitStruct.EXTI_Trigger=EXTI_Trigger_Rising;
	Exti_InitStruct.EXTI_LineCmd=ENABLE;
	EXTI_Init(&Exti_InitStruct);
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_1);
	NVIC_InitStruct.NVIC_IRQChannel=EXTI2_IRQn;
	NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
	NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=0;
	NVIC_InitStruct.NVIC_IRQChannelSubPriority=0;
	NVIC_Init(&NVIC_InitStruct);
	NVIC_InitStruct.NVIC_IRQChannel=EXTI3_IRQn;
	NVIC_InitStruct.NVIC_IRQChannelCmd=ENABLE;
	NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority=1;
	NVIC_InitStruct.NVIC_IRQChannelSubPriority=0;
	NVIC_Init(&NVIC_InitStruct);



}

void EXTI2_IRQHandler(){

	if(EXTI_GetITStatus(EXTI_Line2)!=RESET){
		GPIO_SetBits(GPIOA,GPIO_Pin_2);
		delay(100000);
		GPIO_SetBits(GPIOA,GPIO_Pin_3);
		delay(100000);
		GPIO_SetBits(GPIOA,GPIO_Pin_4);
		delay(100000);
		GPIO_SetBits(GPIOA,GPIO_Pin_5);


	}
	EXTI_ClearITPendingBit(EXTI_Line2);

}



void EXTI3_IRQHandler(){
	if(EXTI_GetITStatus(EXTI_Line3)!=RESET){
			GPIO_SetBits(GPIOA,GPIO_Pin_5);
			delay(100000);
			GPIO_SetBits(GPIOA,GPIO_Pin_4);
			delay(100000);
			GPIO_SetBits(GPIOA,GPIO_Pin_3);
			delay(100000);
			GPIO_SetBits(GPIOA,GPIO_Pin_2);
	}
	EXTI_ClearITPendingBit(EXTI_Line2);

}

void delay(uint32_t t){
	while(t--);
}
int main(void)
{
	Gpio_Config();
	Exti_Config();







  /* TODO - Add your application code here */

  /* Infinite loop */
  while (1)
  {

	  GPIO_ResetBits(GPIOA,GPIO_Pin_All);


}
}


/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);

}



